version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install pytest pytest-cov
  pre_build:
    commands:
      - sam --version
      - python3 --version
      - pip3 --version
  build:
    commands:
      - sam build
  post_build:
    commands:
      - pytest tests/unit/ --cov=hello_world --cov-report=term-missing --cov-report=html --cov-report=lcov

      - sam package --output-template-file packaged.yaml --s3-bucket lambdasrepositoryfromcodepipeline
      - sam deploy --template-file packaged.yaml --stack-name gps-talent-project --s3-bucket lambdasrepositoryfromcodepipeline --capabilities CAPABILITY_NAMED_IAM --region us-east-1
artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*
    - htmlcov/** # Reporte HTML de cobertura
    - lcov.info # Reporte LCOV para SonarQube
  discard-paths: no
