version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install pytest pytest-cov
  build:
    commands:
      - pytest --cov=./ --cov-report=xml
artifacts:
  files:
    - coverage.xml
