version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install pytest pytest-cov
  pre_build:
    commands:
      - sam --version
      - python3 --version
      - pip3 --version

      - export BUILD_ID=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)
      - export S3_PATH="gps-talent-project/$BUILD_ID"
      - echo "S3 Path: $S3_PATH"
      - pytest tests/unit/ --cov=hello_world --cov-report=xml --cov-report=term-missing
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket lambdasrepositoryfromcodepipeline --s3-prefix "$S3_PATH"
  post_build:
    commands:
      - ls -la
      - cat packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name gps-talent-project --s3-bucket lambdasrepositoryfromcodepipeline --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --no-confirm-changeset --force-upload
artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*
    - htmlcov/** # Reporte HTML de cobertura
    - lcov.info # Reporte LCOV para SonarQube
  discard-paths: no
