# Imagen base Alpine 3.16.3
FROM alpine:3.16.3

# Configurar variables de entorno
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV PATH="/home/jenkins/.local/bin:$PATH"

# Instalar dependencias necesarias: Python, AWS SAM CLI, etc.
RUN apk update && apk add --no-cache \
    python3 \
    py3-pip \
    shadow \
    bash \
    curl \
    git \
    zip \
    unzip \
    tar \
    make \
    gcc \
    libc-dev \
    libffi-dev \
    openssl-dev

# Crear grupo y usuario (con Alpine `addgroup` y `adduser`)
RUN addgroup -g 1000 devops && \
    adduser -u 1000 -G devops -h /home/jenkins -s /bin/bash -D jenkins

# Cambiar al usuario creado
USER jenkins

# Directorio de trabajo
WORKDIR /app

# Instalar AWS SAM CLI
RUN pip3 install --upgrade pip && \
    pip3 install aws-sam-cli


RUN mkdir -p jenkins/workspace && chown -R jenkins:devops jenkins
WORKDIR /home/jenkins
RUN mkdir -p .aws && chown -R jenkins:devops .
USER jenkins

# Comando predeterminado: ejecutar SAM build
CMD ["sam", "build"]
