# Imagen base de Amazon Linux 2
FROM amazonlinux:2

# Configurar variables de entorno
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV PATH="/root/.local/bin:$PATH"

# Instalar dependencias del sistema y Python
RUN yum -y update && \
    yum install -y \
    python3 \
    python3-pip \
    zip \
    unzip \
    tar \
    gzip \
    git \
    jq \
    make \
    gcc \
    openssl-devel \
    libffi-devel && \
    yum clean all

# Instalar AWS CLI y AWS SAM CLI
RUN pip3 install --upgrade pip && \
    pip3 install awscli aws-sam-cli

# Crear directorio de trabajo para el proyecto
WORKDIR /app

# Comando predeterminado: ejecutar SAM build
CMD ["sam", "build"]
